# Write your MySQL query statement below
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary
FROM EMPLOYEE E JOIN DEPARTMENT D
ON D.ID = E.DEPARTMENTID
WHERE (E.SALARY, E.DEPARTMENTID) IN(
SELECT MAX(SALARY), DEPARTMENTID
FROM EMPLOYEE
GROUP BY DEPARTMENTID   );